
version: '3.8'

services:
  topcenter-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL}
    ports:
      - "3000:3000"  # Frontend
      - "4000:4000"  # Backend API
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_POCKETBASE_URL=http://pocketbase:8090
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
      - PORT=4000
      - FEATURE_CHATBOT=${FEATURE_CHATBOT:-true}
      - FEATURE_ANALYTICS=${FEATURE_ANALYTICS:-true}
    restart: unless-stopped
    depends_on:
      - mysql
      - pocketbase
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - topcenter-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/db-init:/docker-entrypoint-initdb.d
    networks:
      - topcenter-network

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase-data:/pb_data
    networks:
      - topcenter-network

networks:
  topcenter-network:
    driver: bridge

volumes:
  mysql-data:
  pocketbase-data:
