// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rilzglmuitwpzjqcdyun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpbHpnbG11aXR3cHpqcWNkeXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NzI1MzgsImV4cCI6MjA1MjM0ODUzOH0.F1_W_bRXhdyFDZWartAdZa0IxTh0m06wP-ey6Z5z8WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);